name: Deploy Full Stack to Azure
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Шаг 1: Сборка фронтенда (React)
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
        env:
          CI: false  # Игнорировать предупреждения

      # Шаг 2: Подготовка бэкенда (Python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      # Шаг 3: Деплой всего в Azure Web App
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-app-name'  # Имя вашего App Service
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .  # Корень репозитория (включая /frontend/build и /backend)