name: Deploy to Azure App Service
on:
  push:
    branches: [ "second-part-of-task-5" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'filminfosearch'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './backend'